--- #YAML:1.0
name: InSilicoSpectro-Databanks
version: 0.0.5
author:
  - |-
    Alexandre Masselot <alexandre.masselot@genebio.com>
abstract: |-
  parsing protein/nucleotides sequence databanks (fasta, uniprot...)
license: lgpl
requires:
  Class::Std: 0
  LWP::Simple: 0
  perl: 5.6.1
recommends:
  Bio::Perl: 1.4
  InSilicoSpectro: 0
provides:
  InSilicoSpectro::Databanks:
    file: lib/InSilicoSpectro/Databanks.pm
    version: 0.0.5
  InSilicoSpectro::Databanks::DBEntry:
    file: lib/InSilicoSpectro/Databanks/DBEntry.pm
  InSilicoSpectro::Databanks::DBEntryUniprot:
    file: lib/InSilicoSpectro/Databanks/DBEntryUniprot.pm
generated_by: Module::Build version 0.24
